name: "Run civibuild"

on:
  push:
    branches:
      - gpat
    tags:
  pull_request:

env:
  CIVI_STANDALONE_PHP: ${{ vars.CIVI_STANDALONE_OS || '8.1' }}
  CIVI_STANDALONE_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  civibuild:
    runs-on: 'ubuntu-24.04'

    services:
      mysql:
        image: "mysql:8.1"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval="10s"
          --health-timeout="5s"
          --health-retries="3"

    steps:
      - id: "install-deps"
        name: "Install dependencies"
        shell: bash
        run: |
          sudo add-apt-repository ppa:ondrej/php
          sudo apt-get update
          sudo apt-get install lynx php${{ env.CIVI_STANDALONE_PHP }}
          cd /home/runner
          wget https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh
          bash ./install.sh
          . ./.nvm/nvm.sh
          nvm install 22

      - id: "install-buildkit"
        name: "Install CiviCRM buildkit"
        shell: bash
        run: |
          cd /home/runner
          git clone https://github.com/civicrm/civicrm-buildkit.git ./buildkit
          ./buildkit/bin/civi-download-tools

      - id: "amp-config"
        name: "Configure amp"
        shell: bash
        run: |
          PATH="/home/runner/buildkit/bin:$PATH"
          amp config:set --db_type="mysql_dsn"
          amp config:set --hosts_type="file"
          amp config:set --httpd_type="apache24"
          amp config:set --httpd_restart_command="sudo /usr/sbin/apachectl graceful"
          amp config:set --mysql_dsn="mysql://root@localhost:3306"
          amp config:set --perm_type="worldWritable"
          sudo chmod 666 "/etc/apache2/apache2.conf"
          echo "IncludeOptional /home/runner/.amp/apache.d/*.conf" >> "/etc/apache2/apache2.conf"
          amp test

      - id: "build-instance"
        name: "Build a CiviCRM instance"
        shell: bash
        run: |
          /home/runner/buildkit/bin/civibuild create "civi" \
            --cms-ver "${{ github.repository_owner }}/${{ env.CIVI_STANDALONE_BRANCH_NAME }}" \
            --type "standalone-composer" \
            --url "http://civi.test:8080"

      - id: "post-install"
        name: "Run post-install script"
        shell: bash
        run: |
          bash /home/runner/buildkit/build/civi/web/post-install.sh
